build:
    image: default-bionic
    environment:
        php:
            version: 8.1.13
            pecl_extensions:
                - xdebug
        variables:
            XDEBUG_MODE: "coverage"
            OPENSSL_CFLAGS: "-I/usr/include/openssl"
            OPENSSL_LIBS: "-L/usr/lib/x86_64-linux-gnu -lssl -lcrypto"
    dependencies:
        before:
            - curl -sS https://getcomposer.org/installer | php
            - php composer.phar require --dev phpunit/phpunit ^9
    nodes:
        analysis:
            tests:
                override:
                    - command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
                      coverage:
                        file: clover.xml
                        format: clover
                    - php-scrutinizer-run
        tests: true

filter:
    excluded_paths:
        - 'tests/*'
        - 'example/*'
checks:
    php: true

