# GitHub Action see https://github.com/shivammathur/setup-php
name: Code Analyse
on: [push, pull_request]
jobs:
    unit_tests:
        name: GPWebPay-core (PHP ${{ matrix.php-versions }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-versions: ['7.2', '7.3', '7.4', '8.0']
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: openssl
                  coverage: none #optional
            - name: Composer dependencies
              uses: "ramsey/composer-install@v1"

            - name: Run Codestyle chceck
              run: php vendor/bin/phpcs -p

            - name: Run PHPStan
              run: php vendor/bin/phpstan analyse
