# GitHub Action see https://github.com/shivammathur/setup-php
name: Code Analyse
on: [push, pull_request]
jobs:
    code_quality:
        name: GPWebPay-core (PHP ${{ matrix.php-versions }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-versions: ['8.1', '8.2', '8.3', '8.4']
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: openssl
                  coverage: none #optional
                  tools: composer:v2
            - name: Composer dependencies
              uses: "ramsey/composer-install@v3"

            - name: Run Codestyle chceck
              run: php vendor/bin/phpcs -p

            - name: Run PHPStan
              run: php vendor/bin/phpstan analyse
